api_keys:
  gpt-3.5-turbo-16k:
  gpt-4:
  gpt-4-32k:
  xagentllm:
    - temperature: 1.0
      top_p: 1.0
      repetition_penalty: 1.05


default_request_type: xagent # or xagent
default_completion_kwargs:
  model: xagentllm
  temperature: 1.0
  top_p: 1.0
  request_timeout: 200
  repetition_penalty: 1.05
  max_tokens: 2048

enable_summary: true
summary:
  single_action_max_length: 2048
  max_return_length: 12384

use_selfhost_toolserver: true
selfhost_toolserver_url: http://localhost:8080

max_retry_times: 5
max_subtask_chain_length: 15
max_plan_refine_chain_length: 3
max_plan_tree_depth: 3
max_plan_tree_width: 5
max_plan_length: 8192

rapidapi_retrieve_tool_count: 0

enable_ask_human_for_help: False

tool_blacklist:
  - FileSystemEnv_print_filesys_struture

record_dir:

experiment:
  redo_action: false